stages:
  - build
  - deploy

pages:
  stage: deploy
  script:
    - echo "export const BACKEND_BASE_URL = 'https://www.rezal-mdm.com/api';" > frontend/src/base_url.js
    - /usr/bin/rsync -e 'ssh -p 2223' -atv --delete --exclude 'upload' --exclude '*__pycache__*' --exclude 'frontend/node_modules' --exclude '.git' . rezal@10.100.1.80:/
    - /usr/bin/ssh -p 2223 rezal@10.100.1.80 'update-site'


  rules:
    - if: $CI_COMMIT_BRANCH == "prod"

build-front:
  stage: build #Actually it does not build for now, it only lints
  tags: ["docker"]
  image: node
  script:
    - cd frontend
    - npm ci
    - npm exec -- eslint
    - npm exec -- prettier --check frontend