#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

set -o pipefail

echo Veuillez patientez, vérificaton de votre code...

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff-index --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<EOF
Error: Attempt to add a non-ASCII file name.

This can cause random problems.
If you know what you are doing you can disable this check using:
  git config hooks.allownonascii true
EOF
	exit 1
fi

######################################
##### Début de l'édit custom (avant c'est le template)
######################################

# frontend linting
# TODOs : add prettier; execution conditionnel si on a effectivement touché le front
# Add autofix to eslint
ERRORED=0

# On stash pour ne pas perturber les linters avec ce que vous ne voulez pas commit
# En fait ça n'apporte pas grand chose, donc je vais commenter ça
git stash push --include-untracked --keep-index --quiet -m "Stash de pre-commit"

goToRepoRoot () {
	cd $(git rev-parse --show-toplevel)
}
diffcontains () {
	git diff --staged --name-only | grep "$1" >/dev/null
}

#On ne fait le frontend que si vous y avez touché
goToRepoRoot
if diffcontains "frontend/" ; then
	echo "Vérification des modification frontend..."
	cd frontend
	npm --offline exec -- eslint --fix . || ERRORED=1
	npm --offline exec -- prettier --cache --ignore-path ../.gitignore --write . || ERRORED=1 
else
	echo "Pas de frontend à vérifier"
fi

goToRepoRoot
if diffcontains "backend" ; then
	echo "Vérification des modifications du backend..."
	cd backend
	conda run -n site_rezal -- ruff check --fix --respect-gitignore || ERRORED=1
else
	echo "Pas de backend à vérifier"
fi


goToRepoRoot
git diff --exit-code --quiet || ERRORED=1
if [ $ERRORED -gt 0 ]
then
	echo
	echo Les fichiers suivant ont été modifiés. Veuillez les ré ajouter puis réessayer le commit
	git diff --name-only
fi

# Les guillemets autour du EOF sont importants, sinon les commandes git sont exécutées.
git stash pop --quiet >/dev/null 2>&1 || {
	{ cat <<"EOF"
Les corrections automatiques ont générés des conflits avec les modifications non indexées. Elles ont été abandonné.
EOF
 	} && 
	ERRORED=1;
	git restore --source stash@{0} . --quiet
	git stash drop --quiet
}

exit $ERRORED
